version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    volumes:
      - minecraftdata:/data
      - /e/My Drive/minecraft/factminer2/plugins:/plugins
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "BUKKIT"
      OPS: "KnudHitchhiker"
      ENABLE_WHITELIST: "FALSE"
      ENFORCE_WHITELIST: "FALSE"
      ONLINE_MODE: "FALSE"
      VERSION: "1.19.2"
    tty: true
    stdin_open: true
    restart: unless-stopped
  ngrok:
    env_file: .env.local
    image: wernight/ngrok
    network_mode: host
volumes:
  minecraftdata:
    external: true